---
description: "#{repo}"
builds:
- platform: "linux"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.arch == 'amd64'"

- platform: "linux"
  arch: "386"
  asset_filename: "#{repo}_#{version}_linux_386.tar.gz"
  sha_filename: "#{repo}_#{version}_checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == '386'"

- platform: "osX"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_darwin_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_checksums.txt"
  filter:
  -  "entity.system.os == 'darwin'"
  -  "entity.system.arch == 'amd64'"

- platform: "osX"
  arch: "386"
  asset_filename: "#{repo}_#{version}_darwin_386.tar.gz"
  sha_filename: "#{repo}_#{version}_checksums.txt"
  filter:
  -  "entity.system.os == 'darwin'"
  -  "entity.system.arch == '386'"
